swagger: "2.0"
info:
  description: "API used by mobile apps"
  version: "1.0.0"
  title: "Kino API"
  termsOfService: "http://trionic.cz/terms/"
  contact:
    email: "dev@trionic.cz"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.trionic.cz"
basePath: "/kino/v1"
tags:
- name: "cinema"
  description: "Cinema operations"
- name: "movie"
  description: "Access to movies"
- name: "user"
  description: "Operations about user"
schemes:
- "https"
paths:
  /cinema:
    post:
      tags:
      - "cinema"
      summary: "Add a new cinema"
      description: ""
      operationId: "addCinema"
      security:
      - kino_auth:
        - "write:cinema"
        - "read:cinema"
    put:
      tags:
      - "cinema"
      summary: "Update an existing cinema"
      description: ""
      operationId: "updateCinema"
      security:
      - kino_auth:
        - "write:cinema"
        - "read:cinema"
  /cinema/findByLocation:
    get:
      tags:
      - "cinema"
      summary: "Find cinemas by location"
      description: "Find all cinemas in circle specified by it's center point coordinates (latitude, longitude) and radius"
      operationId: "findCinemasByLocation"
      security:
      - kino_auth:
        - "read:cinema"
  /cinema/{cinemaId}:
    get:
      tags:
      - "cinema"
      summary: "Find cinema by ID"
      description: "Returns a single cinema"
      operationId: "getCinemaById"
      security:
      - api_key: []
    post:
      tags:
      - "cinema"
      summary: "Updates a cinema with form data"
      description: ""
      operationId: "updateCinemaWithForm"
      security:
      - kino_auth:
        - "read:cinema"
        - "write:cinema"
    delete:
      tags:
      - "cinema"
      summary: "Deletes a cinema"
      description: ""
      operationId: "deleteCinema"
      security:
      - kino_auth:
        - "read:cinema"
        - "write:cinema"
  /movie:
    post:
      tags:
      - "movie"
      summary: "Add a new movie"
      description: ""
      operationId: "addMovie"
      security:
      - kino_auth:
        - "write:movie"
    put:
      tags:
      - "movie"
      summary: "Update an existing movie"
      description: ""
      operationId: "updateMovie"
      security:
      - kino_auth:
        - "write:movie"
        - "read:movie"
  /movie/findByTime:
    get:
      tags:
      - "movie"
      summary: "Find movies by time"
      description: "Find N movies with premiere after given time"
      operationId: "findMoviesByTime"
      security:
      - kino_auth:
        - "read:movie"
  /movie/{movieId}:
    get:
      tags:
      - "movie"
      summary: "Find movie by ID"
      description: "Returns a single movie"
      operationId: "getMovieById"
      security:
      - kino_auth:
        - "read:movie"
    post:
      tags:
      - "movie"
      summary: "Updates a movie with form data"
      description: ""
      operationId: "updateMovieWithForm"
      security:
      - kino_auth:
        - "read:movie"
        - "write:movie"
    delete:
      tags:
      - "movie"
      summary: "Deletes a movie"
      description: ""
      operationId: "deleteMovie"
      security:
      - kino_auth:
        - "write:movie"
  /movie/uploadPoster:
    post:
      tags:
      - "movie"
      summary: "uploads an poster image"
      description: ""
      operationId: "uploadPoster"
      security:
      - kino_auth:
        - "write:image"
  /user:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
  /user/createWithArray:
    post:
      tags:
      - "user"
      summary: "Creates list of users with given input array"
      description: ""
      operationId: "createUsersWithArrayInput"
  /user/createWithList:
    post:
      tags:
      - "user"
      summary: "Creates list of users with given input array"
      description: ""
      operationId: "createUsersWithListInput"
  /user/login:
    get:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
  /user/{username}:
    get:
      tags:
      - "user"
      summary: "Get user by user name"
      description: ""
      operationId: "getUserByName"
    put:
      tags:
      - "user"
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
securityDefinitions:
  kino_auth:
    type: "oauth2"
    authorizationUrl: "http://trionic.cz/oauth/dialog"
    flow: "implicit"
    scopes:
      write:cinema: "modify cinema information"
      read:cinema: "read cinema list"
      write:movie: "update movie information"
      read:movie: "read movie list"
      write:image: "upload image"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"